@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@url = http://{{host}}/api/

@token = {{createToken.response.body.$}}
### Get all 
GET {{url}}vacations


### GET image 
GET {{url}}vacations/images/e4910ad4-4d2d-48fc-a628-91ff07268e09.jpg

### Delete 

DELETE  {{url}}vacations/
Authorization: Bearer {{token}}

### Login
# @name createToken
POST {{url}}login
Content-Type: application/json

{
    "email": "bart@gmail.com",
    "password": "1234"
}

### post vacation
POST {{url}}vacations
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="destination"

{{destination}}
--MyBoundary
Content-Disposition: form-data; name="description"

{{description}}
--MyBoundary
Content-Disposition: form-data; name="startDate"

{{startDate}}
--MyBoundary
Content-Disposition: form-data; name="endDate"

{{endDate}}
--MyBoundary
Content-Disposition: form-data; name="price"

{{price}}
--MyBoundary
Content-Disposition: form-data; name="image"; filename="{{imageName}}"
Content-Type: image/jpeg

< C:\Users\misha\Desktop\{{imageName}}
--MyBoundary--

### update


@destination = Queenstown, New Zealand
@description = Adventure capital with bungee jumping, skiing, and stunning landscapes.
@startDate = 2025-12-01
@endDate = 2025-12-10
@price = 4700.00
@imageName = DON'T FORGET.png


PUT {{url}}vacations/5
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="destination"

{{destination}}
--MyBoundary
Content-Disposition: form-data; name="description"

{{description}}
--MyBoundary
Content-Disposition: form-data; name="startDate"

{{startDate}}
--MyBoundary
Content-Disposition: form-data; name="endDate"

{{endDate}}
--MyBoundary
Content-Disposition: form-data; name="price"

{{price}}
--MyBoundary
Content-Disposition: form-data; name="image"; filename="paris.jpg"
Content-Type: image/jpeg

< C:\Users\misha\Desktop\paris.jpg
--MyBoundary--

###
